language: ruby
rvm:
  - 2.2.3
addons:
  postgresql: "9.3"
before_install: gem install bundler -v 1.10.6

install:
  - bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - rspec